"""first

Revision ID: 649b2713ed1a
Revises: e9894e4f4c4c
Create Date: 2023-08-25 06:10:55.502263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b2713ed1a'
down_revision = 'e9894e4f4c4c'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_lablel)s',
    "uq": 'uq_%(table_name)s_%(column_0_name)s',
    "ck": 'ck_%(table_name)s_%(column_0_name)s',
    "fk": 'fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s',
    "pk": 'pk_%(table_name)s',
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('point', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waec_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'waecsubject', ['waec_id'], ['_id'])

    with op.batch_alter_table('waecsubject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waecsubject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=2), nullable=False))
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['_id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('waec_id')

    op.drop_table('grade')
    # ### end Alembic commands ###
