"""Intitial

Revision ID: e9894e4f4c4c
Revises: 
Create Date: 2023-08-25 06:00:37.827260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9894e4f4c4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waec_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waec_subject',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('sub_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
